#!/opt/alt/python311/bin/python
# -*- coding: utf-8 -*-
# Loader CloudLinux — so use se startup file for "passenger_wsgi" (sem .py)
import importlib.util
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)

_path = os.path.join(BASE, "passenger_wsgi.py")
_spec = importlib.util.spec_from_file_location("passenger_wsgi_py", _path)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
application = _mod.application
